remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Benjamin Jones' Portfolio]
description: [This page shows off some of the technology-related projects I've completed aloing with links to the repositories they are contained in]

show_downloads: false

github:
  repository_url: https://github.com/Bnjon01
linkedin_username: benjamin-n-jones
